In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.6)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (9.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.9.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.13.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.10.19)

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"dimaneginsky","key":"6af17c2dd798b5129190b55aef5aea1c"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [37]:
!kaggle competitions download -c titanic

Downloading titanic.zip to /content
100% 34.1k/34.1k [00:00<00:00, 36.2MB/s]

In [39]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [18]:
import pandas as pd
# /content/sample_data
train_data = pd.read_csv('/content/sample_data/sample_data/titanic/train.csv')

**Exercise 1**: Introduction to Data Analysis (Easy)


Objective: Understand the basic overview and significance of data analysis.
Task:
Write a short essay or report on the following topics:

What is data analysis? - A: undestanding of data and its undelrying patterns as well deriving conclusions i the respective context. Composed by descriptive, diagnostic, predictive and prescriptive analysis, and involves data collections, cleaning, exploration, interpretation, visualization, reporting.

Why is data analysis important in modern contexts?
List and describe three areas where data analysis is applied today.
Hint/Tip:
Research current trends in data analysis and real-world examples to provide depth to your essay.
- A: Processes and biology essentially is data and algorithms. Electronic processes nowadays log a lot of data. It's important to analyse this data to resolve bottle-necks, optimize them in order to enable most efficient process execution. Also a lot of decisions (financial investments, marketing/ads, medical treatments) can be informed by relevant predictive data and models and hence increase respective success rate

In [43]:
!unzip credit_card_approvals.zip
!unzip americans_sleep.zip
!unzip global_trends_mentalhealth.zip
#/content/credi_card_approvals.zip

Archive:  credit_card_approvals.zip
  inflating: Credit Card Approvals (Clean Data)/clean_dataset.csv
  inflating: Credit Card Approvals (Clean Data)/crx.csv
Archive:  americans_sleep.zip
  inflating: How Much Sleep Do Americans/Time Americans Spend Sleeping.csv
Archive:  global_trends_mentalhealth.zip
  inflating: Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv

In [72]:
credit_card_df = pd.read_csv('/content/Credit Card Approvals (Clean Data)/clean_dataset.csv')
credit_card_crx_df = pd.read_csv('/content/Credit Card Approvals (Clean Data)/crx.csv')

mental_health_df = pd.read_csv('/content/Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv', index_col=0)

american_sleep_df = pd.read_csv('/content/How Much Sleep Do Americans/Time Americans Spend Sleeping.csv', index_col=0)

/tmp/ipykernel_5067/2196453000.py:4: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health_df = pd.read_csv('/content/Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv', index_col=0)

In [63]:
#type(train_data)
# Exercise 2 + 3: Dataset Loading and Initial Analysis

# Objective: Practice dataset loading from Kaggle and initial analysis.
# Task:
# for the following dataset : How Much Sleep Do Americans Really Get?, Global Trends in Mental Health Disorder and Credit Card Approvals.
# Load the dataset into Jupyter or Google Colab.
# Display the first few rows.
# Provide a brief dataset description.

# Identifying Data Types

# Objective: Learn to identify different data types.
# Task:
# For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

#mental_health_df.head()
#mental_health_df.describe()

#credit_card_df.head()
#credit_card_df.describe()

american_sleep_df.head()

,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
index,,,,,,,,
0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [64]:
american_sleep_df.describe()

              Year  Avg hrs per day sleeping  Standard Error
count   945.000000                945.000000      945.000000
mean   2010.000000                  8.806868        0.086958
std       4.322782                  0.545001        0.034631
min    2003.000000                  7.720000        0.018000
25%    2006.000000                  8.360000        0.063000
50%    2010.000000                  8.810000        0.084000
75%    2014.000000                  9.190000        0.106000
max    2017.000000                 10.650000        0.228000

In [65]:
american_sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 945 entries, 0 to 944
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      945 non-null    int64
 1   Period                    945 non-null    object
 2   Avg hrs per day sleeping  945 non-null    float64
 3   Standard Error            945 non-null    float64
 4   Type of Days              945 non-null    object
 5   Age Group                 945 non-null    object
 6   Activity                  945 non-null    object
 7   Sex                       945 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 66.4+ KB

In [ ]:
# Sleep data:
#  #   Column                    Non-Null Count  Dtype
# ---  ------                    --------------  -----
#  0   Year                      945 non-null    int64    - quantitative
#  1   Period                    945 non-null    object   - qualitative
#  2   Avg hrs per day sleeping  945 non-null    float64  - quantitative
#  3   Standard Error            945 non-null    float64  - quantitative
#  4   Type of Days              945 non-null    object   - qualitative
#  5   Age Group                 945 non-null    object   - qualitative
#  6   Activity                  945 non-null    object   - qualitative
#  7   Sex                       945 non-null    object   - qualitative

In [73]:
credit_card_df.head()
# database of individuals, their credit score rating and various variables that (can)impac that score such as income, employment data, family situation etc.

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [74]:
credit_card_df.describe()

,Gender,Age,Debt,Married,BankCustomer,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,ZipCode,Income,Approved
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000
mean,0.695652,31.514116,4.758725,0.760870,0.763768,2.223406,0.523188,0.427536,2.40000,0.457971,180.547826,1017.385507,0.444928
std,0.460464,11.860245,4.978163,0.426862,0.425074,3.346513,0.499824,0.495080,4.86294,0.498592,173.970323,5210.102598,0.497318
min,0.000000,13.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22.670000,1.000000,1.000000,1.000000,0.165000,0.000000,0.000000,0.00000,0.000000,60.000000,0.000000,0.000000
50%,1.000000,28.460000,2.750000,1.000000,1.000000,1.000000,1.000000,0.000000,0.00000,0.000000,160.000000,5.000000,0.000000
75%,1.000000,37.707500,7.207500,1.000000,1.000000,2.625000,1.000000,1.000000,3.00000,1.000000,272.000000,395.500000,1.000000
max,1.000000,80.250000,28.000000,1.000000,1.000000,28.500000,1.000000,1.000000,67.00000,1.000000,2000.000000,100000.000000,1.000000

In [87]:
credit_card_df.info()
# credit card data
#  Column          Non-Null Count  Dtype
# ---  ------          --------------  -----
#  Gender          690 non-null    int64   - qualitative (boolean)
#  Age             690 non-null    float64 - quantitative
#  Debt            690 non-null    float64 - quantitative
#  Married         690 non-null    int64   - qualitative (boolean)
#  BankCustomer    690 non-null    int64   - qualitative (boolean)
#  Industry        690 non-null    object  - qualitative
#  Ethnicity       690 non-null    object  - qualitative
#  YearsEmployed   690 non-null    float64 - quantitative
#  PriorDefault    690 non-null    int64   - qualitative (boolean)
#  Employed        690 non-null    int64   - qualitative (boolean)
#  CreditScore     690 non-null    int64   - quantitative
#  DriversLicense  690 non-null    int64   - qualitative (boolean)
#  Citizen         690 non-null    object  - qualitative
#  ZipCode         690 non-null    int64   - qualitative
#  Income          690 non-null    int64   - quantitative
#  Approved        690 non-null    int64   - qualitative (boolean)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    object
 6   Ethnicity       690 non-null    object
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    object
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), object(3)
memory usage: 86.4+ KB

In [77]:
#credit_card_crx_df.head(3)
# - some technical summary/stats data, not relevant

   b  30.83     0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.46  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.50  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.54  u  g  w  v  3.75  t   t   5  t   g  00100    3  +

In [78]:
credit_card_crx_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB

In [84]:
mental_health_df.head(3)
# mental_health_df.tail(3)
# by country and year %-values of population suffering from certain mental health issues

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
index,,,,,,,,,,
0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644

In [83]:
mental_health_df.describe()

,Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
count,6468.000000,6468.000000,6468.000000,6468.000000
mean,3.989921,0.862278,3.497654,1.585821
std,1.167526,0.460679,0.655859,0.860283
min,2.023393,0.383650,2.139903,0.446940
25%,3.188824,0.535064,3.005529,0.993685
50%,3.554373,0.726430,3.499606,1.479936
75%,4.682163,0.940157,3.912381,1.867834
max,8.967330,3.452476,6.602754,5.474668

In [85]:
mental_health_df.info()

#  #   Column                     Non-Null Count   Dtype
# ---  ------                     --------------   -----
#  0   Entity                     108553 non-null  object - qualitative
#  1   Code                       103141 non-null  object - qualitative
#  2   Year                       108553 non-null  object - quantitative
#  3   Schizophrenia (%)          25875 non-null   object - quantitative
#  4   Bipolar disorder (%)       19406 non-null   object - quantitative
#  5   Eating disorders (%)       100236 non-null  object - quantitative
#  6   Anxiety disorders (%)      6468 non-null    float64 - quantitative
#  7   Drug use disorders (%)     6468 non-null    float64 - quantitative
#  8   Depression (%)             6468 non-null    float64 - quantitative
#  9   Alcohol use disorders (%)  6468 non-null    float64 - quantitative

<class 'pandas.core.frame.DataFrame'>
Index: 108553 entries, 0 to 108552
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Entity                     108553 non-null  object
 1   Code                       103141 non-null  object
 2   Year                       108553 non-null  object
 3   Schizophrenia (%)          25875 non-null   object
 4   Bipolar disorder (%)       19406 non-null   object
 5   Eating disorders (%)       100236 non-null  object
 6   Anxiety disorders (%)      6468 non-null    float64
 7   Drug use disorders (%)     6468 non-null    float64
 8   Depression (%)             6468 non-null    float64
 9   Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), object(6)
memory usage: 9.1+ MB

In [ ]:
# Exercise 4: Exploring Data Types


# Objective: Learn about different types of data in data analysis.
# Task:
# Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
# Identify and list which columns in your dataset are qualitative and which are quantitative.
# Write a brief description of why each column is classified as qualitative or quantitative.
# Tools: Jupyter Notebook, Python with Pandas library.
!unzip Iris_Dataset.zip

Archive:  Iris_Dataset.zip
replace Iris Dataset/Iris.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [92]:
iris_df = pd.read_csv('/content/Iris Dataset/Iris.csv')
iris_df.head()
iris_df.tail()
# size metrics of some animal/insect species

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [93]:
iris_df.info()
#  #   Column         Non-Null Count  Dtype
# ---  ------         --------------  -----
#  0   Id             150 non-null    int64   - quantitive (can be sorted) but besides order has no further meaning
#  1   SepalLengthCm  150 non-null    float64 - quantitive (measurement)
#  2   SepalWidthCm   150 non-null    float64 - quantitive (measurement)
#  3   PetalLengthCm  150 non-null    float64 - quantitive (measurement)
#  4   PetalWidthCm   150 non-null    float64 - quantitive (measurement)
#  5   Species        150 non-null    object  - qualitiative (categorical, non-number)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [122]:
# Exercise 5: american_sleep_df
# sleeping stats of americans by year, age group, sex, days of the week

In [95]:
american_sleep_df['Age Group'].unique()

array(['15 years and over', '15 to 24 years', '25 to 34 years',
       '35 to 44 years', '45 to 54 years', '55 to 64 years',
       '65 years and over'], dtype=object)

In [96]:
american_sleep_df['Type of Days'].unique()

array(['All days', 'Nonholiday weekdays', 'Weekend days and holidays'],
      dtype=object)

**Exercise 5**: Basic Observation Skills in Data Analysis
Objective: Develop observation skills for data analysis.
Task:
Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
Tools: Jupyter Notebook, Python with Pandas library.

Answer: Group comparison: by age group (younger, older..), by days of the week (holiday/weekend vs nonholiday weekdays), sec (female vs male)
Trends could be analyzed vs year - whether it's been changing over the years. Also by age group as a categorical variable that could be connverted to numerical one as it's 10-year groups

**Exercise 6:** Identifying Data Types
Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file. - **structured**

Photographs uploaded to a social media platform.       - **unstructured**

A collection of news articles on a website.            - **unstructured**

Inventory data in a relational database.               - **structured**

Recorded interviews from a market research study.      - **unstructured**

**Exercise 7**: Transformation Exercise
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences. - A: Categorize and document by location, date/year of travel, travel period, travel length, travel overall experience rating (qualitatively or bag og words scoring). So, that the trips become comparable.

Audio recordings of customer service calls. - A: call date, call length, call topic, resolution y/n/pending etc., customer type, gender, age.. -> Will help identify patterns who requests support, what topics most often, how long are the calls, how many -> resources planning.

Handwritten notes from a brainstorming session. - A: list of topics, person(s) discussing a topic, priority of each topic, topic's business impact, tools for implementation, effort estimates for implementation

A video tutorial on cooking. - A: ingredients table w ingredient name, weight/amount, id (lowest the first to be used), cooking phase as part of the whole preparation.

In [97]:
!unzip train.zip

Archive:  train.zip
  inflating: train.csv

In [100]:
#Exercise 8
# Import the train dataset. Use the train.csv file.
# Print the first few rows of the DataFrame.
train_data_df = pd.read_csv('/content/train.csv')
train_data_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [114]:
# Exercise 9 : Export a dataframe to excel format and JSON format.
# Create a simple dataframe.
# Export the dataframe to an excel file.
# Export the dataframe to a JSON file.

test_dict = {
    'python_fundamentals': [15,1],
    'statistics': [8,2],
    'data_analysis': [10,(3,5)],
    'supervised_learning': [10,5]
}
print([test_dict])
# test_df = pd.DataFrame([test_dict])
test_df = pd.DataFrame.from_dict(test_dict, orient='index', columns=['hours', 'week'])

test_df.to_excel('test_df.xlsx')
test_df.to_json('test_df.json')

[{'python_fundamentals': [15, 1], 'statistics': [8, 2], 'data_analysis': [10, (3, 5)], 'supervised_learning': [10, 5]}]

In [115]:
test_df

                     hours    week
python_fundamentals     15       1
statistics               8       2
data_analysis           10  (3, 5)
supervised_learning     10       5

In [121]:
# Exercise 10: Reading JSON Data
# Use a sample JSON dataset

# Import the JSON data from the provided URL.
# Use Pandas to read the JSON data.
# Display the first five entries of the data.

#posts_df=pd.read_json('/content/posts.json')
posts_df=pd.read_json('https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip')
#posts_df=pd.read_json('https://jsonplaceholder.typicode.com/posts')
posts_df.head(5)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...